on:
  pull_request:
    branches: ['main']

jobs:
  python-settlement:
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Test Python
        run: |
          pip install pytest
          pytest ./tests